### ISSUE TITLE
Standard Architecture 5.2.0 parameter existing_sm_instance_region filled with wrong value

### ISSUE THREAD

**Issue by jobgitmww** [terraform-ibm-modules/terraform-ibm-powervs-infrastructure#878]
Using version 5.2.0 Standard Architecture via Projects/Schematics the existing_sm_instance_region parameter is filled with the wrong value. 

In Projects I selected eu-de but Schmatics is filled with eu-es. Consequently the deployment fails. 

### Affected modules
2024/06/25 14:51:47 Terraform apply | Error: CreateSecretGroupWithContext failed Post "https://d5065978-0463-4ffe-b771-61cc5733f2f9.eu-es.secrets-manager.appdomain.cloud/api/v2/secret_groups": dial tcp: lookup d5065978-0463-4ffe-b771-61cc5733f2f9.eu-es.secrets-manager.appdomain.cloud on 172.21.0.10:53: no such host
 2024/06/25 14:51:47 Terraform apply | null
 2024/06/25 14:51:47 Terraform apply | 
 2024/06/25 14:51:47 Terraform apply | 
 2024/06/25 14:51:47 Terraform apply |   with module.standard.module.secrets_manager_group[0].ibm_sm_secret_group.secret_group,
 2024/06/25 14:51:47 Terraform apply |   on .terraform/modules/standard.secrets_manager_group/main.tf line 8, in resource "ibm_sm_secret_group" "secret_group":
 2024/06/25 14:51:47 Terraform apply |    8: resource "ibm_sm_secret_group" "secret_group" {
 2024/06/25 14:51:47 Terraform apply | 
 2024/06/25 14:51:48 [1m[31mTerraform APPLY error: Terraform APPLY errorexit status 1[39m[0m
*

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by surajsbharadwaj** [comment]
@jobgitmww this has been fixed now. Please add the required version again to project and it generate a plan it should work now.
